### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by dyhBUPT** [Alexadlu/IDF#1]
Hi, thansk for your excellent works for nighttime ReID.

Would you please release codes for evaluation on datasets Knight / Night600 / RGBNT201_rgb / Syn_Dark, and your methods IDF (TMM2023) and CENet (arxiv2023)？

Thank you very much!

**Comment by Alexadlu** [comment]
Thank you for your interest in our nighttime ReID work.

Regarding your request to release the evaluation code on the Knight/Night600 / RGBNT201_rgb/Syn_Dark dataset, and our methods IDF (TMM2023) and CENet (arxiv2023), we currently have the code for the IDF work publicly available.
The code for CENet is still in preparation, and we will update it on the GitHub repository once the code is ready. Keep an eye out for any updates in our repository.

**Comment by dyhBUPT** [comment]
Thank you very much~
